### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by CZL-96** [Wslsdx/Deep-Learning-Approach-for-Surface-Defect-Detection#28]
Could you tell me how to deal with this kind of problem when training

2020-06-21 22:49:36.547439: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2020-06-21 22:49:36.550579: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2020-06-21 22:49:36.553213: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8797 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "run.py", line 140, in <module>
    main()
  File "run.py", line 136, in main
    agent=Agent(param)
  File "E:\目标检测\Deep-Learning-Approach-for-Surface-Defect-Detection-master\agent.py", line 15, in __init__
    self.init_datasets()  #初始化数据管理器
  File "E:\目标检测\Deep-Learning-Approach-for-Surface-Defect-Detection-master\agent.py", line 30, in init_datasets
    self.Positive_data_list,self.Negative_data_list=self.listData1(self.__Param["data_dir"])
  File "E:\目标检测\Deep-Learning-Approach-for-Surface-Defect-Detection-master\agent.py", line 170, in listData1
    example_dirs = [x[1] for x in os.walk(data_dir)][0]
IndexError: list index out of range

**Comment by ZhangZhiHao233** [comment]
It maybe the problem about your datasets.

**Comment by Vogeeker** [comment]
> Could you tell me how to deal with this kind of problem when training
> 
> 2020-06-21 22:49:36.547439: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988] 0
> 2020-06-21 22:49:36.550579: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0: N
> 2020-06-21 22:49:36.553213: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8797 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
> Traceback (most recent call last):
> File "run.py", line 140, in
> main()
> File "run.py", line 136, in main
> agent=Agent(param)
> File "E:\目标检测\Deep-Learning-Approach-for-Surface-Defect-Detection-master\agent.py", line 15, in **init**
> self.init_datasets() #初始化数据管理器
> File "E:\目标检测\Deep-Learning-Approach-for-Surface-Defect-Detection-master\agent.py", line 30, in init_datasets
> self.Positive_data_list,self.Negative_data_list=self.listData1(self.__Param["data_dir"])
> File "E:\目标检测\Deep-Learning-Approach-for-Surface-Defect-Detection-master\agent.py", line 170, in listData1
> example_dirs = [x[1] for x in os.walk(data_dir)][0]
> IndexError: list index out of range

I Solve the problem by change the dir.  Not  (../xxx/xxx), but(./xxx/xxx)
